//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mirk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkUserGroup
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdGroup { get; set; }
        public Nullable<int> IsAdmin { get; set; }
        public Nullable<int> IsFavorite { get; set; }
        public Nullable<int> IsNotNotificated { get; set; }
        public Nullable<int> NotificationNumber { get; set; }
    }
}
